"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const middlewares_1 = require("middlewares");
const book_schema_1 = require("schemas/book.schema");
const book_controller_1 = require("controller/book.controller");
const bookRouter = (0, express_1.Router)();
bookRouter.post("/", middlewares_1.middlewares.validate(book_schema_1.bookZodSchema), book_controller_1.bookController.createBook);
bookRouter.get("/", middlewares_1.middlewares.validate(book_schema_1.bookQuerySchema), book_controller_1.bookController.getBooks);
bookRouter.get("/:bookId", book_controller_1.bookController.getBookById);
bookRouter.put("/:bookId", middlewares_1.middlewares.validate(book_schema_1.updateBookSchema), book_controller_1.bookController.updateBook);
bookRouter.delete("/:bookId", book_controller_1.bookController.deleteBook);
exports.default = bookRouter;
